# Generated by Django 4.0.4 on 2022-05-13 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=250, null=True, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_no', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], default='Male', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.IntegerField(blank=True, max_length=6, null=True)),
                ('street_address', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='media/patientImages')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.IntegerField(blank=True, max_length=6, null=True)),
                ('clinic_address', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='media/doctorImages')),
                ('doctor_certificate', models.ImageField(blank=True, null=True, upload_to='media/doctorImages')),
                ('about', models.TextField(blank=True, null=True)),
                ('specialist', models.CharField(choices=[('Sports Medicine Specialists', 'Sports Medicine Specialists'), ('General Surgeons', 'General Surgeons'), ('Allergists/ Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Cardiologists', 'Cardiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons'), ('Critical Care Medicine Specialists', 'Critical Care Medicine Specialists'), ('Dermatologists', 'Dermatologists'), ('Endocrinologists', 'Endocrinologists'), ('Urologists', 'Urologists'), ('Rheumatologists', 'Rheumatologists'), ('Radiologists', 'Radiologists'), ('Pulmonologists', 'Pulmonologists'), ('Psychiatrists', 'Psychiatrists'), ('Preventive Medicine Specialists', 'Preventive Medicine Specialists'), ('Podiatrists', 'Podiatrists'), ('Plastic Surgeons', 'Plastic Surgeons'), ('Physiatrists', 'Physiatrists'), ('Pediatricians', 'Pediatricians'), ('Pathologists', 'Pathologists'), ('Otolaryngologists', 'Otolaryngologists'), ('Osteopaths', 'Osteopaths'), ('Ophthalmologists', 'Ophthalmologists'), ('Oncologists', 'Oncologists'), ('Obstetricians and Gynecologists', 'Obstetricians and Gynecologists'), ('Neurologists', 'Neurologists'), ('Nephrologists', 'Nephrologists'), ('Medical Geneticists', 'Medical Geneticists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Others', 'Others')], default='Sports Medicine Specialists', max_length=255)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.usermodel')),
            ],
        ),
    ]
