# Generated by Django 4.0.4 on 2022-05-17 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('appointment_type', models.CharField(choices=[('Emergency', 'Emergency'), ('Normal', 'Normal')], default='Normal', max_length=100, null=True)),
                ('slots', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('appointment_type', models.CharField(choices=[('Emergency', 'Emergency'), ('Normal', 'Normal')], default='Normal', max_length=100, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('clinic_address', models.TextField()),
                ('profile_image', models.ImageField(blank=True, default='media/doctorImages/default.png', null=True, upload_to='media/doctorImages')),
                ('doctor_certificate', models.ImageField(blank=True, null=True, upload_to='media/doctorImages')),
                ('about', models.TextField(blank=True, null=True)),
                ('specialist', models.CharField(choices=[('Sports Medicine Specialists', 'Sports Medicine Specialists'), ('General Surgeons', 'General Surgeons'), ('Allergists/ Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Cardiologists', 'Cardiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons'), ('Critical Care Medicine Specialists', 'Critical Care Medicine Specialists'), ('Dermatologists', 'Dermatologists'), ('Endocrinologists', 'Endocrinologists'), ('Urologists', 'Urologists'), ('Rheumatologists', 'Rheumatologists'), ('Radiologists', 'Radiologists'), ('Pulmonologists', 'Pulmonologists'), ('Psychiatrists', 'Psychiatrists'), ('Preventive Medicine Specialists', 'Preventive Medicine Specialists'), ('Podiatrists', 'Podiatrists'), ('Plastic Surgeons', 'Plastic Surgeons'), ('Physiatrists', 'Physiatrists'), ('Pediatricians', 'Pediatricians'), ('Pathologists', 'Pathologists'), ('Otolaryngologists', 'Otolaryngologists'), ('Osteopaths', 'Osteopaths'), ('Ophthalmologists', 'Ophthalmologists'), ('Oncologists', 'Oncologists'), ('Obstetricians and Gynecologists', 'Obstetricians and Gynecologists'), ('Neurologists', 'Neurologists'), ('Nephrologists', 'Nephrologists'), ('Medical Geneticists', 'Medical Geneticists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Others', 'Others')], default='Sports Medicine Specialists', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.TextField(null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.bookappointment')),
            ],
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('doctor_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctorusermodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], default='Male', max_length=10)),
                ('usertype', models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], default='Patient', max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SlotsTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('slottiming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.slots')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reports_image', models.ImageField(null=True, upload_to='media/reports')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='PatientUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('street_address', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, default='media/patientImages/default.png', null=True, upload_to='media/patientImages')),
                ('gov_id_type', models.CharField(choices=[('Asdhar Card', 'Aadhar Card'), ('Voter Id Card', 'Voter Id Card'), ('Passport Id', 'Passposrt Id'), ('Pan Card', 'Pan Card'), ('Others', 'Others')], max_length=100, null=True)),
                ('gov_id_no', models.CharField(max_length=255, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.usermodel')),
            ],
        ),
        migrations.AddField(
            model_name='doctorusermodel',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.usermodel'),
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctorusermodel'),
        ),
    ]
