# Generated by Django 4.0.4 on 2022-05-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorusermodel',
            old_name='clinic_address',
            new_name='street_address',
        ),
        migrations.AlterField(
            model_name='patientusermodel',
            name='gov_id_type',
            field=models.CharField(choices=[('Aadhar Card', 'Aadhar Card'), ('Voter Id Card', 'Voter Id Card'), ('Passport Id', 'Passposrt Id'), ('Pan Card', 'Pan Card'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
