# Generated by Django 4.0.4 on 2022-05-14 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_usermodel_email_remove_usermodel_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='unique_id',
        ),
    ]
