# Generated by Django 4.0.4 on 2022-05-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_usermodel_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='usertype',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], default='Patient', max_length=100, null=True),
        ),
    ]
