# Generated by Django 4.0.4 on 2022-05-15 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_usermodel_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('appointment_type', models.CharField(choices=[('Emergency', 'Emergency'), ('Normal', 'Normal')], default='Normal', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.TextField(null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.bookappointment')),
            ],
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='patientusermodel',
            name='gov_id_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientusermodel',
            name='gov_id_type',
            field=models.CharField(choices=[('Asdhar Card', 'Aadhar Card'), ('Voter Id Card', 'Voter Id Card'), ('Passport Id', 'Passposrt Id'), ('Pan Card', 'Pan Card'), ('Others', 'Others')], default='Aadhar Card', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorusermodel',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/doctorImages/default.png', null=True, upload_to='media/doctorImages'),
        ),
        migrations.AlterField(
            model_name='patientusermodel',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/patientImage/default.png', null=True, upload_to='media/patientImages'),
        ),
        migrations.CreateModel(
            name='SlotsTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('slottiming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.slots')),
            ],
        ),
        migrations.AddField(
            model_name='slots',
            name='doctor_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctorusermodel'),
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reports_image', models.ImageField(null=True, upload_to='media/reports')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.prescription')),
            ],
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='slots',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.slots'),
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='user_appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
