# Generated by Django 4.0.4 on 2022-05-15 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_bookappointment_prescription_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='user_appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctorusermodel'),
        ),
    ]
